name: 'Kubernetes Cluster Deploy '
description: 'test '
inputs:
  KUBECONFIG:  # kubeconfig
    description: 'Cluster Kubeconfig File'
    required: false
    default: 'default'
  dPath: # deployment yaml path
    description: 'deployment file path '
    required: false
    default: 'default'
  dName: # deployment.yaml
    description: 'deployment file name'
    required: false
    default: 'deployment.yaml'
outputs:
  Result:
    description: "Deploy  step results"
    value: "Build steps  finished"
runs:
  using: "composite"
  steps:
    - name: Repository Files are downloading
      uses: actions/checkout@v2
    - name: echo kubeconfig input
    - run : python ${{ github.action_path }}/main.py --kubeConfig "${{inputs.KUBECONFIG}}" -dp ${{inputs.dPath}} -dn ${{inputs.dName}}
      shell: bash

